# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'InstagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for InstagramClone
#  pod 'Firebase/Core'
#pod 'FirebaseAuth'
#pod 'FirebaseFirestore'

  target 'InstagramCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagramCloneUITests' do
    # Pods for testing
  end

end
